name: AWS OIDC Connect Demo GA
on:
  push
env:
  AWS_REGION : "eu-west-2"   
permissions:
      id-token: write
      contents: read
jobs:
  DemoOIDC:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ vars.ARN }}
          role-session-name: ${{ secrets.ROLENAME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Print AWS SSM Parameter
        run: aws ssm get-parameter --name=hello_aws-gh-oidc --query Parameter.Value

      - name: Print assumed role
        run: aws sts get-caller-identity